#!/bin/bash

: ${CATALINA_CONNECTOR_PROXYNAME:=bamboo}
: ${CATALINA_CONNECTOR_PROXYPORT:=443}
: ${CATALINA_CONNECTOR_SCHEME:=https}

: ${CATALINA_OPTS:=}
CATALINA_OPTS="${CATALINA_OPTS} -DcatalinaConnectorProxyName=${CATALINA_CONNECTOR_PROXYNAME}"
CATALINA_OPTS="${CATALINA_OPTS} -DcatalinaConnectorProxyPort=${CATALINA_CONNECTOR_PROXYPORT}"
CATALINA_OPTS="${CATALINA_OPTS} -DcatalinaConnectorScheme=${CATALINA_CONNECTOR_SCHEME}"

export CATALINA_OPTS
exec bin/start-bamboo.sh -fg
